# Site settings
title: Ahmed Heakl
email: ahmed.heakl@mbzuai.ac.ae
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision Researcher at Mohamed Bin Zayed University of Artificial Intelligence
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ahmedheakl.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Navigation
navigation:
  - title: About
    url: "#about"
  - title: Publications
    url: "#publications"
  - title: News
    url: "#news"
  - title: Academic Service
    url: "#service"

# Social links
github_username: ahmedheakl
google_scholar: JcWO9OUAAAAJ

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
